steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/dtu-mlops-project-410911/test', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dtu-mlops-project-410911/test']