workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/dtu-mlops-project-410911/train_image:latest
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY