name: Train model
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: iterative/setup-cml@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
      - uses: iterative/setup-dvc@v1
      - name: Get data
        run: dvc pull
        env:
            GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      - name: Train model
        run: |
          python dog_breed_identification/train_cml.py
      - name: Write report
        env:
          # this authenticates that the right permissions are in place
          REPO_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cat reports/figures/classification_report.txt >> report.md
          echo "![confusion_matrix](reports/figures/confusion_matrix.png)" >> report.md
          cml comment create report.md