name: Deploy API

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      PROJECT_ID: dtu-mlops-project-410911
      GCP_CREDENTIALS: ${{ secrets.DATA_BUCKET_SERVICE_ACCOUNT_2 }}
      CONTAINER_NAME: dog-breed-identification-api
      SERVICE_NAME: dog-breed-identification-api
    
    steps:
    - name: Google Cloud Authentication
      uses: google-github-actions/auth@v1
      with: 
        credentials_json: ${{ env.GCP_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - uses: 'gcr.io/cloud-builders/docker'
      name: Build docker image

    - name: 'gcr.io/cloud-builders/docker'
      run: 'push gcr.io/${{ env.PROJECT_ID }}/${{ env.CONTAINER_NAME }}:latest'
  
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      run: 'gcloud run deploy ${{ env.SERVICE_NAME }} --image gcr.io/${{ env.PROJECT_ID }}/${{ env.CONTAINER_NAME }}:latest --region europe-west1'
