name: DVC Pull from Google Cloud Storage

on:
  push:
    branches:
      - "*"

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.DATA_BUCKET_SERVICE_ACCOUNT }}
          export_default_credentials: true
      - name: DVC Pull
        run: |
          dvc pull
