name: DVC pulling and testing

on:
  workflow_dispatch:

jobs:
  test-and-deploy-to-staging:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install dvc
        python -m pip install "dvc[gs]"
        pip install -r requirements.txt

    - name: Gcp Auth
      uses: 'google-github-actions/auth@v1'
      with: 
        credentials_json: '${{ secrets.DATA_BUCKET_SERVICE_ACCOUNT_2 }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: 'Pull DVC'
      run: dvc pull

    - name: Test model
      run: pytest