name: Manual Model Training Workflow

env:
  ENVIRONMENT: cpu

on:
  workflow_dispatch:

jobs:
  connect-to_gcp:
    runs-on: ubuntu-latest
    steps:
    - name: Gcp Auth
      uses: 'google-github-actions/auth@v1'
      with: 
        credentials_json: '${{ secrets.DATA_BUCKET_SERVICE_ACCOUNT_2 }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'
    - name: 'Start Model Training'
      run: |
        gcloud ai custom-jobs create \
        --region=europe-west1 \
        --display-name=test-run \
        --config=$ENVIRONMENT_config.yaml